### ISSUE TITLE
automate build based on yaml

### ISSUE THREAD

**Issue by kamilsk** [octomation/vanity#1]
- [x] define the structure
```yaml
sources:
- pkg: go.octolab.org
  go-import: { vcs: git, path: https://github.com/octolab/pkg}
  go-source: { path: https://github.com/octolab/pkg, file: https://github.com/octolab/pkg/tree/master{/dir} line: https://github.com/octolab/pkg/tree/master{/dir}/{file}#L{line}}
- ...
```
- [x] implement builder
